//$file${controller::.::qm_controller.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dcc.qm
// File:  ${controller::.::qm_controller.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${controller::.::qm_controller.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef __CONTROLLER_H__
#define __CONTROLLER_H__

#include "qp_signals.h"

//$declare${controller} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::controller} ..................................................
typedef struct {
// protected:
    QMActive super;
} controller;

// protected:
QState controller_initial(controller * const me, void const * const par);
QState controller_error  (controller * const me, QEvt const * const e);
QState controller_error_e(controller * const me);
extern QMState const controller_error_s;
QState controller_operation  (controller * const me, QEvt const * const e);
QState controller_operation_i(controller * const me);
extern QMState const controller_operation_s;
QState controller_startup  (controller * const me, QEvt const * const e);
QState controller_startup_e(controller * const me);
extern QMState const controller_startup_s;
QState controller_ready  (controller * const me, QEvt const * const e);
QState controller_ready_e(controller * const me);
extern QMState const controller_ready_s;

//${controller::controller_ctor} .............................................
uint32_t controller_ctor(void);

//${controller::package::dcc_message} ........................................
typedef struct {
// protected:
    QEvt super;

// public:
    uint8_t data[DCC_MAX_PACKET_LEN];;
    uint8_t size;
} dcc_message;
//$enddecl${controller} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif  /* __CONTROLLER_H__ */

