//$file${controller::.::qm_controller.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dcc.qm
// File:  ${controller::.::qm_controller.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${controller::.::qm_controller.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qm_controller.h"

Q_DEFINE_THIS_MODULE("Controller")

/* PRIVATE VARIABLES DEFINITIONS */

static controller controller_inst;

/* PUBLIC VARIABLES DEFINITIONS */

QActive * const ao_controller = &controller_inst.super.super;

/* PRIVATE FUNCTIONS DECLARATIONS */

/* AO DEFINITIONS */

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${controller} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${controller::controller} ..................................................

//${controller::controller::SM} ..............................................
QState controller_initial(controller * const me, void const * const par) {
    //${controller::controller::SM::initial}

    QS_FUN_DICTIONARY(&controller_error);
    QS_FUN_DICTIONARY(&controller_operation);
    QS_FUN_DICTIONARY(&controller_startup);
    QS_FUN_DICTIONARY(&controller_ready);

    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &controller_operation_s, // target state
        {
            Q_ACTION_CAST(&controller_operation_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${controller::controller::SM::error} .......................................
QMState const controller_error_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&controller_error),
    Q_ACTION_CAST(&controller_error_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${controller::controller::SM::error}
QState controller_error_e(controller * const me) {
    static const QEvt motor_e_break_evt = {EMERGENCY_BRAKE_SIG, 0u, 0u};

    QACTIVE_POST(ao_motor, &motor_e_break_evt, me);
    return QM_ENTRY(&controller_error_s);
}
//${controller::controller::SM::error}
QState controller_error(controller * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${controller::controller::SM::operation} ...................................
QMState const controller_operation_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&controller_operation),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_CAST(&controller_operation_i)
};
//${controller::controller::SM::operation::initial}
QState controller_operation_i(controller * const me) {
    //${controller::controller::SM::operation::initial}
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &controller_startup_s, // target state
        {
            Q_ACTION_CAST(&controller_startup_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${controller::controller::SM::operation}
QState controller_operation(controller * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${controller::controller::SM::operation::startup} ..........................
QMState const controller_startup_s = {
    &controller_operation_s, // superstate
    Q_STATE_CAST(&controller_startup),
    Q_ACTION_CAST(&controller_startup_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${controller::controller::SM::operation::startup}
QState controller_startup_e(controller * const me) {
    /* TODO: Implement POST */

    /* TODO: Remove after testing */
    static const QEvt evt = QEVT_INITIALIZER(CNTRL_RECONFIGURE_SIG);

    QACTIVE_POST(ao_controller, &evt, me);
    return QM_ENTRY(&controller_startup_s);
}
//${controller::controller::SM::operation::startup}
QState controller_startup(controller * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${controller::controller::SM::operation::startup::CNTRL_RECONFIGURE}
        case CNTRL_RECONFIGURE_SIG: {
            uint32_t status = NO_ERROR;
            //${controller::controller::SM::operation::startup::CNTRL_RECONFIGUR~::[Configerror]}
            if (NO_ERROR != status) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &controller_error_s, // target state
                    {
                        Q_ACTION_CAST(&controller_error_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${controller::controller::SM::operation::startup::CNTRL_RECONFIGUR~::[noerror]}
            else {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &controller_ready_s, // target state
                    {
                        Q_ACTION_CAST(&controller_ready_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${controller::controller::SM::operation::ready} ............................
QMState const controller_ready_s = {
    &controller_operation_s, // superstate
    Q_STATE_CAST(&controller_ready),
    Q_ACTION_CAST(&controller_ready_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${controller::controller::SM::operation::ready}
QState controller_ready_e(controller * const me) {
    /* TODO: Correct to the right Evt type */
    static const QEvt evt = QEVT_INITIALIZER(DECODER_START_SIG);

    QACTIVE_POST(ao_decoder, &evt, me);
    return QM_ENTRY(&controller_ready_s);
}
//${controller::controller::SM::operation::ready}
QState controller_ready(controller * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${controller::controller::SM::operation::ready::DCC_MESSAGE}
        case DCC_MESSAGE_SIG: {
            dcc_message const * const dcc_msg = Q_EVT_CAST(dcc_message);

            decode(dcc_msg->data, dcc_msg->size, true);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${controller::controller_ctor} .............................................
uint32_t controller_ctor(void) {
    uint32_t res = NO_ERROR;

    controller * const me = &controller_inst;

    QMActive_ctor(&me->super, Q_STATE_CAST(&controller_initial));

    QS_OBJ_DICTIONARY(ao_controller);
    QS_SIG_DICTIONARY(CNTRL_RECONFIGURE_SIG, me);
    QS_SIG_DICTIONARY(DCC_MESSAGE_SIG, me);

    return res;
}
//$enddef${controller} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

