//$file${decoder::.::qm_decoder.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dcc.qm
// File:  ${decoder::.::qm_decoder.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${decoder::.::qm_decoder.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef __DECODER_H__
#define __DECODER_H__

#include "qp_signals.h"

//$declare${decoder::decoder} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${decoder::decoder} ........................................................
typedef struct {
// protected:
    QMActive super;

// public:

    /* Number of bits received so far */
    uint8_t bit_cnt;

    /* Value of the byte under reception */
    uint8_t rec_byte;

    /* Number of bytes received so far */
    uint8_t byte_cnt;
    uint8_t * rx_buffer;
} decoder;

// protected:
QState decoder_initial(decoder * const me, void const * const par);
QState decoder_init  (decoder * const me, QEvt const * const e);
extern QMState const decoder_init_s;
QState decoder_decoding  (decoder * const me, QEvt const * const e);
QState decoder_decoding_e(decoder * const me);
QState decoder_decoding_x(decoder * const me);
QState decoder_decoding_i(decoder * const me);
extern QMState const decoder_decoding_s;
QState decoder_preamble  (decoder * const me, QEvt const * const e);
QState decoder_preamble_e(decoder * const me);
extern QMState const decoder_preamble_s;
QState decoder_byte  (decoder * const me, QEvt const * const e);
QState decoder_byte_e(decoder * const me);
extern QMState const decoder_byte_s;
//$enddecl${decoder::decoder} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${decoder::decoder_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${decoder::decoder_ctor} ...................................................
uint32_t decoder_ctor(void);
//$enddecl${decoder::decoder_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif  /* __DECODER_H__ */
