//$file${decoder::.::qm_decoder.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dcc.qm
// File:  ${decoder::.::qm_decoder.h}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${decoder::.::qm_decoder.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef __DECODER_H__
#define __DECODER_H__

#include "qp_signals.h"

//$declare${decoder::decoder} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${decoder::decoder} ........................................................
typedef struct {
// protected:
    QMActive super;

// public:

    /* Number of bits received so far */
    uint8_t bit_cnt;

    /* Value of the byte under reception */
    uint8_t rec_byte;

    /* Number of bytes received so far */
    uint8_t byte_cnt;
    uint8_t * rx_buffer;
} decoder;

// protected:
QState decoder_initial(decoder * const me, void const * const par);
QState decoder_init  (decoder * const me, QEvt const * const e);
extern QMState const decoder_init_s;
QState decoder_decoding  (decoder * const me, QEvt const * const e);
QState decoder_decoding_e(decoder * const me);
QState decoder_decoding_x(decoder * const me);
QState decoder_decoding_i(decoder * const me);
extern QMState const decoder_decoding_s;
QState decoder_preamble  (decoder * const me, QEvt const * const e);
QState decoder_preamble_e(decoder * const me);
extern QMState const decoder_preamble_s;
QState decoder_byte  (decoder * const me, QEvt const * const e);
QState decoder_byte_e(decoder * const me);
extern QMState const decoder_byte_s;
//$enddecl${decoder::decoder} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${decoder::decoder_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${decoder::decoder_ctor} ...................................................
uint32_t decoder_ctor(void);
//$enddecl${decoder::decoder_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif  /* __DECODER_H__ */
