//$file${decoder::.::qm_decoder.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dcc.qm
// File:  ${decoder::.::qm_decoder.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${decoder::.::qm_decoder.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qm_decoder.h"
#include "decoder.h"

#include "bsp.h"

Q_DEFINE_THIS_MODULE("Decoder")

#define MIN_PREAMBLE_LEN    ((uint32_t) 11u)        /* Minimum lenght of the preamble*/

/* PRIVATE VARIABLES DEFINITIONS */

static decoder decoder_inst;

/* PUBLIC VARIABLES DEFINITIONS */

QActive * const ao_decoder = &decoder_inst.super.super;

/* PRIVATE FUNCTIONS DECLARATIONS */

/* PRIVATE FUNCTIONS DEFINITIONS */

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${decoder::decoder} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${decoder::decoder} ........................................................

//${decoder::decoder::SM} ....................................................
QState decoder_initial(decoder * const me, void const * const par) {
    //${decoder::decoder::SM::initial}

    QS_FUN_DICTIONARY(&decoder_init);
    QS_FUN_DICTIONARY(&decoder_decoding);
    QS_FUN_DICTIONARY(&decoder_preamble);
    QS_FUN_DICTIONARY(&decoder_byte);

    static QMTranActTable const tatbl_ = { // tran-action table
        &decoder_init_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${decoder::decoder::SM::init} ..............................................
QMState const decoder_init_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&decoder_init),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${decoder::decoder::SM::init}
QState decoder_init(decoder * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${decoder::decoder::SM::init::DECODER_START}
        case DECODER_START_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &decoder_decoding_s, // target state
                {
                    Q_ACTION_CAST(&decoder_decoding_e), // entry
                    Q_ACTION_CAST(&decoder_decoding_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${decoder::decoder::SM::decoding} ..........................................
QMState const decoder_decoding_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&decoder_decoding),
    Q_ACTION_CAST(&decoder_decoding_e),
    Q_ACTION_CAST(&decoder_decoding_x),
    Q_ACTION_CAST(&decoder_decoding_i)
};
//${decoder::decoder::SM::decoding}
QState decoder_decoding_e(decoder * const me) {
    BSP_StartDCCTimer();
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&decoder_decoding_s);
}
//${decoder::decoder::SM::decoding}
QState decoder_decoding_x(decoder * const me) {
    BSP_StopDCCTimer();
    (void)me; // unused parameter
    return QM_EXIT(&decoder_decoding_s);
}
//${decoder::decoder::SM::decoding::initial}
QState decoder_decoding_i(decoder * const me) {
    //${decoder::decoder::SM::decoding::initial}
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &decoder_preamble_s, // target state
        {
            Q_ACTION_CAST(&decoder_preamble_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${decoder::decoder::SM::decoding}
QState decoder_decoding(decoder * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${decoder::decoder::SM::decoding::DECODER_STOP}
        case DECODER_STOP_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &decoder_init_s, // target state
                {
                    Q_ACTION_CAST(&decoder_decoding_x), // exit
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${decoder::decoder::SM::decoding::DECODER_RST}
        case DECODER_RST_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[4];
            } const tatbl_ = { // tran-action table
                &decoder_decoding_s, // target state
                {
                    Q_ACTION_CAST(&decoder_decoding_x), // exit
                    Q_ACTION_CAST(&decoder_decoding_e), // entry
                    Q_ACTION_CAST(&decoder_decoding_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${decoder::decoder::SM::decoding::preamble} ................................
QMState const decoder_preamble_s = {
    &decoder_decoding_s, // superstate
    Q_STATE_CAST(&decoder_preamble),
    Q_ACTION_CAST(&decoder_preamble_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${decoder::decoder::SM::decoding::preamble}
QState decoder_preamble_e(decoder * const me) {
    me->bit_cnt = 0u;
    me->rec_byte = 0u;
    me->byte_cnt = 0u;
    return QM_ENTRY(&decoder_preamble_s);
}
//${decoder::decoder::SM::decoding::preamble}
QState decoder_preamble(decoder * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${decoder::decoder::SM::decoding::preamble::BIT_0}
        case BIT_0_SIG: {
            //${decoder::decoder::SM::decoding::preamble::BIT_0::[len>=11]}
            if (me->bit_cnt >= MIN_PREAMBLE_LEN) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &decoder_byte_s, // target state
                    {
                        Q_ACTION_CAST(&decoder_byte_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${decoder::decoder::SM::decoding::preamble::BIT_0::[len<11]}
            else {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &decoder_preamble_s, // target state
                    {
                        Q_ACTION_CAST(&decoder_preamble_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        //${decoder::decoder::SM::decoding::preamble::BIT_1}
        case BIT_1_SIG: {
            me->bit_cnt++;
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${decoder::decoder::SM::decoding::byte} ....................................
QMState const decoder_byte_s = {
    &decoder_decoding_s, // superstate
    Q_STATE_CAST(&decoder_byte),
    Q_ACTION_CAST(&decoder_byte_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${decoder::decoder::SM::decoding::byte}
QState decoder_byte_e(decoder * const me) {
    me->bit_cnt = 0u;
    me->rec_byte = 0u;
    return QM_ENTRY(&decoder_byte_s);
}
//${decoder::decoder::SM::decoding::byte}
QState decoder_byte(decoder * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${decoder::decoder::SM::decoding::byte::BIT_1}
        case BIT_1_SIG: {
            me->bit_cnt++;
            //${decoder::decoder::SM::decoding::byte::BIT_1::[8bits]}
            if (me->bit_cnt > 8) {
                post_dcc_message(me);
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &decoder_preamble_s, // target state
                    {
                        Q_ACTION_CAST(&decoder_preamble_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${decoder::decoder::SM::decoding::byte::BIT_1::[else]}
            else {
                me->rec_byte <<= 1u;
                me->rec_byte |= 1u;
                status_ = QM_HANDLED();
            }
            break;
        }
        //${decoder::decoder::SM::decoding::byte::BIT_0}
        case BIT_0_SIG: {
            me->bit_cnt++;
            //${decoder::decoder::SM::decoding::byte::BIT_0::[8bits]}
            if (me->bit_cnt > 8) {
                me->rx_buffer[me->byte_cnt] = me->rec_byte;

                me->byte_cnt++;

                Q_ASSERT(me->byte_cnt <= DCC_MAX_PACKET_LEN);
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &decoder_byte_s, // target state
                    {
                        Q_ACTION_CAST(&decoder_byte_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${decoder::decoder::SM::decoding::byte::BIT_0::[else]}
            else {
                me->rec_byte <<= 1u;
                status_ = QM_HANDLED();
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${decoder::decoder} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/* PUBLIC FUNCTIONS DEFINITIONS */

//$define${decoder::decoder_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${decoder::decoder_ctor} ...................................................
uint32_t decoder_ctor(void) {
    uint32_t res = NO_ERROR;

    decoder * const me = &decoder_inst;

    decoder_reset();

    QMActive_ctor(&me->super, Q_STATE_CAST(&decoder_initial));

    QS_OBJ_DICTIONARY(ao_decoder);
    QS_SIG_DICTIONARY(DECODER_START_SIG, me);
    QS_SIG_DICTIONARY(DECODER_STOP_SIG, me);
    QS_SIG_DICTIONARY(DECODER_RST_SIG, me);

    decoder_aux_dict();

    return res;
}
//$enddef${decoder::decoder_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

