//$file${functions::.::qm_functions.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dcc.qm
// File:  ${functions::.::qm_functions.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${functions::.::qm_functions.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qp_signals.h"

//$declare${functions::functions} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${functions::functions} ....................................................
typedef struct {
// protected:
    QMActive super;

// private state histories
    QMState const *hist_PORTA_CHIUSA;
} functions;

// protected:
static QState functions_initial(functions * const me, void const * const par);
static QState functions_PORTA_CHIUSA  (functions * const me, QEvt const * const e);
static QState functions_PORTA_CHIUSA_x(functions * const me);
static QMState const functions_PORTA_CHIUSA_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&functions_PORTA_CHIUSA),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_CAST(&functions_PORTA_CHIUSA_x),
    Q_ACTION_NULL  // no initial tran.
};
static QState functions_ACCESO  (functions * const me, QEvt const * const e);
static QMState const functions_ACCESO_s = {
    &functions_PORTA_CHIUSA_s, // superstate
    Q_STATE_CAST(&functions_ACCESO),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
static QState functions_PORTA_APERTA  (functions * const me, QEvt const * const e);
static QMState const functions_PORTA_APERTA_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&functions_PORTA_APERTA),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${functions::functions} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${functions::functions} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${functions::functions} ....................................................

//${functions::functions::SM} ................................................
static QState functions_initial(functions * const me, void const * const par) {
    //${functions::functions::SM::initial}
    // state history attributes
    me->hist_PORTA_CHIUSA = &functions_ACCESO_s;

    QS_FUN_DICTIONARY(&functions_PORTA_CHIUSA);
    QS_FUN_DICTIONARY(&functions_ACCESO);
    QS_FUN_DICTIONARY(&functions_PORTA_APERTA);

    static QMTranActTable const tatbl_ = { // tran-action table
        &functions_PORTA_CHIUSA_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${functions::functions::SM::PORTA_CHIUSA} ..................................
//${functions::functions::SM::PORTA_CHIUSA}
static QState functions_PORTA_CHIUSA_x(functions * const me) {
    // save deep history
    me->hist_PORTA_CHIUSA = QMsm_stateObj(Q_MSM_UPCAST(me));
    return QM_EXIT(&functions_PORTA_CHIUSA_s);
}
//${functions::functions::SM::PORTA_CHIUSA}
static QState functions_PORTA_CHIUSA(functions * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${functions::functions::SM::PORTA_CHIUSA::SEGANLE PORTA APERTA}
        case SEGANLE PORTA APERTA_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &functions_PORTA_APERTA_s, // target state
                {
                    Q_ACTION_CAST(&functions_PORTA_CHIUSA_x), // exit
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${functions::functions::SM::PORTA_CHIUSA::ACCENDI}
        case ACCENDI_SIG: {
            static QMTranActTable const tatbl_ = { // tran-action table
                &functions_ACCESO_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${functions::functions::SM::PORTA_CHIUSA::ACCESO} ..........................
//${functions::functions::SM::PORTA_CHIUSA::ACCESO}
static QState functions_ACCESO(functions * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${functions::functions::SM::PORTA_CHIUSA::ACCESO::SPEGNI}
        case SPEGNI_SIG: {
            static QMTranActTable const tatbl_ = { // tran-action table
                &functions_PORTA_CHIUSA_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${functions::functions::SM::PORTA_APERTA} ..................................
//${functions::functions::SM::PORTA_APERTA}
static QState functions_PORTA_APERTA(functions * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${functions::functions::SM::PORTA_APERTA::SEGNALE PORTA CHIUSA}
        case SEGNALE PORTA CHIUSA_SIG: {
            static QMTranActTable const tatbl_ = { // tran-action table
                &functions_PORTA_CHIUSA_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_HIST(me->hist_PORTA_CHIUSA, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${functions::functions} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
