//$file${motor::.::qm_motor.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dcc.qm
// File:  ${motor::.::qm_motor.h}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${motor::.::qm_motor.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef __MOTOR_H__
#define __MOTOR_H__

#include "qp_signals.h"

/**/

#define SPEED_STEPS ((uint8_t) 28u)

enum motor_direction {
    DIRECTION_BACKWARD = 0u,
    DIRECTION_FORWARD = 1u
};

enum acceleration_dir {
    SPEED_INCREASE = 0u,
    SPEED_DECREASE
};

//$declare${motor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${motor::package::motor_config} ............................................
typedef struct {
// public:

    /* CV#2: Vstart */
    uint8_t v_start;

    /* CV#3: Acceleration Rate */
    uint8_t acc_rate;

    /* CV#4: Deceleration Rate */
    uint8_t dec_rate;

    /* CV#9: Total PWM Period */
    uint8_t pwm_t;

    /* CV#23: Acceleration Adjustment */
    uint8_t acc_adj;

    /* CV#24: Deceleration Adjustment */
    uint8_t dec_adj;

    /* CV#67-94: Speed Table */
    uint8_t speed_tab[28];
} motor_config;

//${motor::package::motor_cfg_evt} ...........................................
/* Event used to configure the motor AO */
typedef struct {
// protected:
    QEvt super;

// public:
    motor_config config;
} motor_cfg_evt;

//${motor::package::speed_evt} ...............................................
/* Event used to Set/Update the speed of the motor */
typedef struct {
// protected:
    QEvt super;

// public:
    int16_t speed;
    uint8_t direction;
} speed_evt;

//${motor::motor} ............................................................
typedef struct {
// protected:
    QMActive super;

// private:

    /* Acceleration/deceleration timer */
    QTimeEvt accel_timer;
    uint16_t speed_table_len;
    uint8_t const * speed_table;

    /* Motor configuration */
    motor_config * configuration;

    /* Period between two speed steps during acceleration [ms] */
    uint32_t accel_t;

    /* Period between two speed steps during deceleration     [ms] */
    uint32_t decel_t;
    uint32_t pwm_arr;

    /* Actual speed steps. When microstepping, it's the _lower_ step */
    uint8_t actual_step;

    /* Next step: substepping will move towards this value */
    uint8_t next_step;

    /* Target speed step */
    uint8_t target_step;

    /* Substep counter, used for substepping */
    uint8_t substp_cnt;

    /* Number of substeps for the current substepping sequence */
    uint8_t substp_num;

    /* Shif factor for computing substep PWM duty cycle */
    uint8_t substp_lsr;

    /* Difference in pwm value between actual and next speed step */
    uint16_t delta_pwm;

    /* Base PWM value used for substepping */
    uint16_t actual_pwm;

    /* Direction of stepping and substepping */
    enum acceleration_dir accel_dir;

// public:

    /* time in milliseconds between substeps */
    uint16_t t_substp;

// private:
    enum motor_direction direction;

    /* Queue used to store CHANGE_SPEED event that requires reversal of direction */
    QEQueue zeroCrossingQueue;
} motor;

// protected:
QState motor_initial(motor * const me, void const * const par);
QState motor_operation  (motor * const me, QEvt const * const e);
QState motor_operation_i(motor * const me);
extern QMState const motor_operation_s;
QState motor_init  (motor * const me, QEvt const * const e);
extern QMState const motor_init_s;
QState motor_configured  (motor * const me, QEvt const * const e);
extern QMState const motor_configured_s;
QState motor_running  (motor * const me, QEvt const * const e);
QState motor_running_i(motor * const me);
extern QMState const motor_running_s;
QState motor_stop  (motor * const me, QEvt const * const e);
QState motor_stop_e(motor * const me);
extern QMState const motor_stop_s;
QState motor_e_stop  (motor * const me, QEvt const * const e);
QState motor_e_stop_e(motor * const me);
extern QMState const motor_e_stop_s;
QState motor_change  (motor * const me, QEvt const * const e);
QState motor_change_e(motor * const me);
QState motor_change_x(motor * const me);
extern QMState const motor_change_s;
QState motor_cruise  (motor * const me, QEvt const * const e);
extern QMState const motor_cruise_s;
QState motor_error  (motor * const me, QEvt const * const e);
extern QMState const motor_error_s;

//${motor::motor_ctor} .......................................................
/* Constructor for Motor controller AO */
uint32_t motor_ctor(void);
//$enddecl${motor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif  /* __MOTOR_H__ */

