//$file${motor::.::qm_motor.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: dcc.qm
// File:  ${motor::.::qm_motor.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${motor::.::qm_motor.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qm_motor.h"
#include "motor.h"

Q_DEFINE_THIS_MODULE("QM_Motor")

#define ACCEL_TIMER_PERIOD ((uint32_t) 10u)    /**< 10 ms period for the acceleration timer */
#define TIMER_TICK_RATE    ((uint8_t) 0u)      /**< tick rate used for the timers */
#define MOTOR_ACCELERATION ((int16_t) 1)       /**< To be defined */
#define FAULT_TIMEOUT      ((uint16_t)1500u)   /**< Max fault duration: 1.5 s */

/* PRIVATE VARIABLES DEFINITIONS */

static motor motor_inst;

static QEvt const * zcQueue[1u];

/* PUBLIC VARIABLES DEFINITIONS */

QActive * const ao_motor = &motor_inst.super.super;

/* PRIVATE FUNCTIONS DECLARATIONS */

uint32_t motor_speed_set(int16_t speed);

/* PRIVATE FUNCTIONS DEFINITIONS */

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${motor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${motor::motor} ............................................................

//${motor::motor::SM} ........................................................
QState motor_initial(motor * const me, void const * const par) {
    //${motor::motor::SM::initial}

    QS_FUN_DICTIONARY(&motor_operation);
    QS_FUN_DICTIONARY(&motor_init);
    QS_FUN_DICTIONARY(&motor_configured);
    QS_FUN_DICTIONARY(&motor_running);
    QS_FUN_DICTIONARY(&motor_stop);
    QS_FUN_DICTIONARY(&motor_e_stop);
    QS_FUN_DICTIONARY(&motor_change);
    QS_FUN_DICTIONARY(&motor_cruise);
    QS_FUN_DICTIONARY(&motor_error);

    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &motor_operation_s, // target state
        {
            Q_ACTION_CAST(&motor_operation_i), // initial tran.
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${motor::motor::SM::operation} .............................................
QMState const motor_operation_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&motor_operation),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_CAST(&motor_operation_i)
};
//${motor::motor::SM::operation::initial}
QState motor_operation_i(motor * const me) {
    //${motor::motor::SM::operation::initial}
    static QMTranActTable const tatbl_ = { // tran-action table
        &motor_init_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${motor::motor::SM::operation}
QState motor_operation(motor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${motor::motor::SM::operation::MOTOR_FAULT_ASSERT}
        case MOTOR_FAULT_ASSERT_SIG: {
            /* Arm the timer */
            QTimeEvt_armX(&me->fault_timer, (FAULT_TIMEOUT), 0u);
            status_ = QM_HANDLED();
            break;
        }
        //${motor::motor::SM::operation::MOTOR_FAULT_CLEAR}
        case MOTOR_FAULT_CLEAR_SIG: {
            QTimeEvt_disarm(&me->fault_timer);
            status_ = QM_HANDLED();
            break;
        }
        //${motor::motor::SM::operation::FAULT_TIMEOUT}
        case FAULT_TIMEOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &motor_error_s, // target state
                {
                    Q_ACTION_CAST(&motor_error_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            //${motor::motor::SM::operation::CATCH_ALL}
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &motor_error_s, // target state
                {
                    Q_ACTION_CAST(&motor_error_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
    }
    return status_;
}

//${motor::motor::SM::operation::init} .......................................
QMState const motor_init_s = {
    &motor_operation_s, // superstate
    Q_STATE_CAST(&motor_init),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${motor::motor::SM::operation::init}
QState motor_init(motor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${motor::motor::SM::operation::init::MOTOR_CONFIG}
        case MOTOR_CONFIG_SIG: {
            uint32_t err = NO_ERROR;

            err = configure_motor(me, e);
            //${motor::motor::SM::operation::init::MOTOR_CONFIG::[error]}
            if (NO_ERROR != err) {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &motor_error_s, // target state
                    {
                        Q_ACTION_CAST(&motor_error_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            //${motor::motor::SM::operation::init::MOTOR_CONFIG::[noerror]}
            else {
                static QMTranActTable const tatbl_ = { // tran-action table
                    &motor_configured_s, // target state
                    {
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${motor::motor::SM::operation::configured} .................................
QMState const motor_configured_s = {
    &motor_operation_s, // superstate
    Q_STATE_CAST(&motor_configured),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${motor::motor::SM::operation::configured}
QState motor_configured(motor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${motor::motor::SM::operation::configured::MOTOR_CTRL_START}
        case MOTOR_CTRL_START_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &motor_running_s, // target state
                {
                    Q_ACTION_CAST(&motor_running_i), // initial tran.
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${motor::motor::SM::operation::running} ....................................
QMState const motor_running_s = {
    &motor_operation_s, // superstate
    Q_STATE_CAST(&motor_running),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_CAST(&motor_running_i)
};
//${motor::motor::SM::operation::running::initial}
QState motor_running_i(motor * const me) {
    //${motor::motor::SM::operation::running::initial}
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &motor_stop_s, // target state
        {
            Q_ACTION_CAST(&motor_stop_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}
//${motor::motor::SM::operation::running}
QState motor_running(motor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${motor::motor::SM::operation::running::MOTOR_CTRL_RECONFIGURE}
        case MOTOR_CTRL_RECONFIGURE_SIG: {
            static QMTranActTable const tatbl_ = { // tran-action table
                &motor_configured_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${motor::motor::SM::operation::running::EMERGENCY_BRAKE}
        case EMERGENCY_BRAKE_SIG: {
            /* Flush the queue since an emergency brake has been requested.
             * This prevents event being posted by entering the super-state "stop" */
            QActive_flushDeferred(ao_motor, &me->zeroCrossingQueue, Q_DIM(zcQueue));
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &motor_e_stop_s, // target state
                {
                    Q_ACTION_CAST(&motor_stop_e), // entry
                    Q_ACTION_CAST(&motor_e_stop_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${motor::motor::SM::operation::running::CHANGE_SPEED}
        case CHANGE_SPEED_SIG: {
            speed_evt const * const s_evt = Q_EVT_CAST(speed_evt);

            /* Flush the queue since a newer value has been requested */
            QActive_flushDeferred(ao_motor, &me->zeroCrossingQueue, Q_DIM(zcQueue));

            /* Is the motor stopped? (Stop or E-Stop) */
            if (0u == me->speed_table[me->actual_step]) {

                /* Yes, simply update target speed and direction */
                me->target_step = s_evt->speed;
                me->direction = s_evt->direction;

            } else if (s_evt->direction == me->direction) {

                /* When direction is the same, simply update target speed */
                me->target_step = s_evt->speed;

            }
            else {

                /* When direction is different, first stop */
                me->target_step = 0u;

                /* Defer this event for when entering the stop state */
                QActive_defer(ao_motor, &me->zeroCrossingQueue, e);

            }
            //${motor::motor::SM::operation::running::CHANGE_SPEED::[at_speed]}
            if (is_at_speed(me)) {
                status_ = QM_HANDLED();
            }
            //${motor::motor::SM::operation::running::CHANGE_SPEED::[else]}
            else {
                static struct {
                    QMState const *target;
                    QActionHandler act[2];
                } const tatbl_ = { // tran-action table
                    &motor_change_s, // target state
                    {
                        Q_ACTION_CAST(&motor_change_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        //${motor::motor::SM::operation::running::SET_SPEED}
        case SET_SPEED_SIG: {
            speed_evt const * const s_evt = Q_EVT_CAST(speed_evt);

            Q_REQUIRE(s_evt->speed < SPEED_STEPS);

            me->actual_step = s_evt->speed;
            me->direction = s_evt->direction;

            motor_reset_substeps(me);

            motor_pwm_set(me->actual_pwm, me->direction);
            static QMTranActTable const tatbl_ = { // tran-action table
                &motor_cruise_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${motor::motor::SM::operation::running::stop} ..............................
QMState const motor_stop_s = {
    &motor_running_s, // superstate
    Q_STATE_CAST(&motor_stop),
    Q_ACTION_CAST(&motor_stop_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${motor::motor::SM::operation::running::stop}
QState motor_stop_e(motor * const me) {
    /* Recall events, if any, that requested an inversion */
    QActive_recall(ao_motor, &me->zeroCrossingQueue);

    //motor_speed_set(0);
    return QM_ENTRY(&motor_stop_s);
}
//${motor::motor::SM::operation::running::stop}
QState motor_stop(motor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${motor::motor::SM::operation::running::stop::e_stop} ......................
QMState const motor_e_stop_s = {
    &motor_stop_s, // superstate
    Q_STATE_CAST(&motor_e_stop),
    Q_ACTION_CAST(&motor_e_stop_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${motor::motor::SM::operation::running::stop::e_stop}
QState motor_e_stop_e(motor * const me) {
    emergency_brake();
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&motor_e_stop_s);
}
//${motor::motor::SM::operation::running::stop::e_stop}
QState motor_e_stop(motor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${motor::motor::SM::operation::running::stop::e_stop::EMERGENCY_BRAKE_RELEASE}
        case EMERGENCY_BRAKE_RELEASE_SIG: {
            static QMTranActTable const tatbl_ = { // tran-action table
                &motor_stop_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            //${motor::motor::SM::operation::running::stop::e_stop::CATCH_ALL}
            status_ = QM_HANDLED();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${motor::motor::SM::operation::running::change} ............................
QMState const motor_change_s = {
    &motor_running_s, // superstate
    Q_STATE_CAST(&motor_change),
    Q_ACTION_CAST(&motor_change_e),
    Q_ACTION_CAST(&motor_change_x),
    Q_ACTION_NULL  // no initial tran.
};
//${motor::motor::SM::operation::running::change}
QState motor_change_e(motor * const me) {
    /* New speed is not the actual speed (or substep counter is not zeor)
     * so update substepping parameters
     */
    compute_substep_param(me);

    /* Arm the timer */
    QTimeEvt_armX(&me->accel_timer, me->t_substp, me->t_substp);
    return QM_ENTRY(&motor_change_s);
}
//${motor::motor::SM::operation::running::change}
QState motor_change_x(motor * const me) {
    QTimeEvt_disarm(&me->accel_timer);
    return QM_EXIT(&motor_change_s);
}
//${motor::motor::SM::operation::running::change}
QState motor_change(motor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${motor::motor::SM::operation::running::change::SPEED_REACHED}
        case SPEED_REACHED_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[2];
            } const tatbl_ = { // tran-action table
                &motor_cruise_s, // target state
                {
                    Q_ACTION_CAST(&motor_change_x), // exit
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${motor::motor::SM::operation::running::change::MOTOR_STOPPED}
        case MOTOR_STOPPED_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &motor_stop_s, // target state
                {
                    Q_ACTION_CAST(&motor_change_x), // exit
                    Q_ACTION_CAST(&motor_stop_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        //${motor::motor::SM::operation::running::change::SPEED_TIMER}
        case SPEED_TIMER_SIG: {
            static QEvt const stopped = {MOTOR_STOPPED_SIG, 0u, 0u};
            static QEvt const cruise = {SPEED_REACHED_SIG, 0u, 0u};
            QEvt const * evt = NULL;
            uint16_t pwm = 0u;

            /* Change actual speed towards the desired speed cruise */
            /* 1. Acceleration or Deceleration? */
            if (SPEED_INCREASE == me->accel_dir) {
                me->substp_cnt++;
            } else {
                me->substp_cnt--;
            }

            /* 2. Compute PWM duty cycle */
            pwm = me->actual_pwm + ((me->substp_cnt * me->delta_pwm) >> me->substp_lsr);

            /* 3. And set it in the peripheral */
            motor_pwm_set(pwm, me->direction);

            /* 4. Integer speed reached? */
            if (((me->substp_cnt == me->substp_num) && (SPEED_INCREASE == me->accel_dir)) ||
                ((0u == me->substp_cnt) && (SPEED_DECREASE == me->accel_dir))) {

                /* 5. Update actual speed step */
                me->actual_step = me->next_step;

                /* 6. Target speed reached? */
                if (me->actual_step == me->target_step) {

                    /* 6A. Yes, send speed_reached/stopped signal */
                    if (0u == me->speed_table[me->actual_step]) {
                        evt = &stopped;
                    } else {
                        evt = &cruise;
                    }
                    QACTIVE_POST(ao_motor, evt, ao_motor);
                } else {

                    /* 6B. No, compute the parameters for next sub-stepping sequence*/
                    compute_substep_param(me);

                    /* 7. Re-arm the timer */
                    QTimeEvt_rearm(&me->accel_timer, me->t_substp);
                }
            }
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${motor::motor::SM::operation::running::cruise} ............................
QMState const motor_cruise_s = {
    &motor_running_s, // superstate
    Q_STATE_CAST(&motor_cruise),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${motor::motor::SM::operation::running::cruise}
QState motor_cruise(motor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${motor::motor::SM::error} .................................................
QMState const motor_error_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&motor_error),
    Q_ACTION_CAST(&motor_error_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${motor::motor::SM::error}
QState motor_error_e(motor * const me) {
    emergency_brake();

    /* TODO: Inform the controller */
    Q_UNUSED_PAR(me);
    return QM_ENTRY(&motor_error_s);
}
//${motor::motor::SM::error}
QState motor_error(motor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${motor::motor_ctor} .......................................................
uint32_t motor_ctor(void) {
    uint32_t res = NO_ERROR;

    motor * const me = &motor_inst;

    QMActive_ctor(&me->super, Q_STATE_CAST(&motor_initial));

    me->actual_step = 0u;
    me->target_step = 0u;
    me->next_step = 0u;
    me->direction = DIRECTION_FORWARD;
    me->accel_dir = MOTOR_ACCELERATION;

    QTimeEvt_ctorX(&me->accel_timer, ao_motor, SPEED_TIMER_SIG, TIMER_TICK_RATE);
    QTimeEvt_ctorX(&me->fault_timer, ao_motor, FAULT_TIMEOUT_SIG, TIMER_TICK_RATE);

    QEQueue_init(&me->zeroCrossingQueue, zcQueue, Q_DIM(zcQueue));

    QS_OBJ_DICTIONARY(ao_motor);

    QS_SIG_DICTIONARY(MOTOR_CONFIG_SIG, me);
    QS_SIG_DICTIONARY(MOTOR_CTRL_START_SIG, me);
    QS_SIG_DICTIONARY(MOTOR_CTRL_RECONFIGURE_SIG, me);
    QS_SIG_DICTIONARY(CHANGE_SPEED_SIG, me);
    QS_SIG_DICTIONARY(SET_SPEED_SIG, me);
    QS_SIG_DICTIONARY(EMERGENCY_BRAKE_SIG, me);
    QS_SIG_DICTIONARY(MOTOR_STOPPED_SIG, me);
    QS_SIG_DICTIONARY(SPEED_REACHED_SIG, me);
    QS_SIG_DICTIONARY(SPEED_TIMER_SIG, me);

    return res;
}
//$enddef${motor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/* PUBLIC FUNCTIONS DEFINITIONS */
